# Generated by Django 4.0.3 on 2022-04-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0002_alter_node_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='freespace',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
