# Generated by Django 4.0.3 on 2022-04-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0004_alter_tree_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='p2p_app.tree'),
        ),
    ]
